### ISSUE TITLE
Browser bottom panel doesn't work with Kythe v0.0.31 (and later)

### ISSUE THREAD

**Issue by kamahen** [TreeTide/underhood#12]
With Kythe v0.0.31, the browser bottom panel doesn't show anything when an anchor is clicked or moused-over. It works for Kythe v0.0.30.

To reproduce: 
* Download [pykythe](https://github.com/kamahen/pykythe).
* Edit the Makefile's ENTRYSTREAM_EXE, WRITE_ENTRIES_EXE, etc. 
  * The Makefile points VERIFIER_EXE to the executable generated from the Kythe source tree - this is only for getting Kythe [PR 4199](https://github.com/kythe/kythe/pull/4199), which is a cosmetic change to the verifier "?" output -- you can use /opt/kythe/tools/verifier if you wish.
* Run make target `run-underhood-all`.
 * You may prefer running the individual commands in separate windows, to make clean-up easier.

Here is an example URL for browising:
`http://localhost:9000/#/file/kythe:%2F%2Ftest-corpus%3Froot=test-root%3Fpath=tmp%2Fpykythe_test%2FSUBST%2Fhome%2Fpeter%2Fsrc%2Fpykythe%2Ftest_data%2Fbindings.py`

**Comment by kamahen** [comment]
To save you the trouble of installing SWI-Prolog, here is a tar archive of /tmp/pykythe_test, which includes the serving tables (v0.0.30) and the .json files. (It has a .txt suffix to git past github's UI)
[pykythe_test_tables.tar.bz2.txt](https://github.com/TreeTide/underhood/files/3849750/pykythe_test_tables.tar.bz2.txt)

To process this (assuming you put it in /tmp):
```
set -o pipefail; \
    cat $(find /tmp/pykythe_test/KYTHE -name '*.kythe.json') | \
    egrep -v '^{"fact_name":"/pykythe/symtab"' | \
    /opt/kythe/tools/entrystream --read_format=json | \
    /opt/kythe/tools/write_entries -graphstore /tmp/pykythe_test/graphstore
/opt/kythe/tools/write_tables -graphstore=/tmp/pykythe_test/graphstore -out=/tmp/pykythe_test/tables

```

**Comment by kamahen** [comment]
Oops, that was the wrong file (it was the tables). Anyway, what you want are the *.kythe.json files, which are attached here.
[pykythe_test_json.tar.bz2.txt](https://github.com/TreeTide/underhood/files/3849773/pykythe_test_json.tar.bz2.txt)

(I'd attach the entire directory, but github limits me to about 10MB)

**Comment by kamahen** [comment]
Is there anything I could provide you that would make it easier for you to reproduce the issue? For example, would it be easier if I gave you a single test file output (either JSON or kythe protobuf) with its source?

**Comment by kamahen** [comment]
Does Underhood work for C++, Java, etc. with Kythe v0.0.31 and later?

**Comment by robinp** [comment]
I see in the past I did some API changes for Kythe compatibility in the https://github.com/TreeTide/underhood/tree/robinp-calls branch. Let me have a look if that branch fixes it, and if so, merge.

**Comment by kamahen** [comment]
I did a quick test with the robinp-calls branch and it didn't fix the problem.

**Comment by kamahen** [comment]
A few of my Kythe facts are wrong (no corpus and root). I will re-run things to see if that makes any difference to the browser.

**Comment by kamahen** [comment]
I'm still seeing the same problem. Attached are updated .json files.
[pykythe_test_json.tar.bz2.txt](https://github.com/TreeTide/underhood/files/3971652/pykythe_test_json.tar.bz2.txt)

**Comment by robinp** [comment]
Sorry for letting this rest! Looking into this now.

**Comment by kamahen** [comment]
No rush ... I decided to write my own browser and server because I want to explore some other things. (I was surprised how far I can get with bare Javascript ... it's a surprising amount of work to set up environments for things like Vue and read the documentation for using them without "cargo culting")

This small patch might help you figure out what's going on (also the reply in https://github.com/kythe/kythe/issues/4128#issuecomment-567710797 although I wasn't sure how to interpret it):
```diff
--- a/kythe/go/serving/xrefs/xrefs.go
+++ b/kythe/go/serving/xrefs/xrefs.go
@@ -515,6 +515,7 @@ func (t *Table) CrossReferences(ctx context.Context, req *xpb.CrossReferencesReq
 		ticket := tickets[i]
 		cr, err := t.crossReferences(ctx, ticket)
 		if err == table.ErrNoSuchKey {
+			log.Printf("WARNING: NoSuchKey: %s", ticket)
 			continue
 		} else if err != nil {
 			return nil, canonicalError(err, "cross-references", ticket)
```

**Comment by robinp** [comment]
Fun! Please post some screenshots if you find something interesting.

Vue is the least cargo culted, has nice docs actually. But I agree that setting up a whole JS transpilation pipeline with Webpack, Babel and pals is mind-bending. Lots of copy-pasting fragments from outdated documentation, progressing error-by-error.

But luckily Bazel workspace rules served as great preparation for these exercise :P

**Comment by kamahen** [comment]
For my browser, I'm working out a few mistakes in my pipeline and in generating HTML (which I'd have regardless of whether I use Vue or something else). At my current rate of progress, I should have something that you can play with in a couple of weeks. (But I seem to have picked up a virus over the holidays whose main symptoms are on-and-off headaches and fatigue, so "a couple of weeks" might be optimistic).

My solution uses SWI-Prolog, which is easily installed on Ubuntu using a [PPA](https://www.swi-prolog.org/build/PPA.html). (Also Python 3.7, which has its own [PPA](https://linuxize.com/post/how-to-install-python-3-7-on-ubuntu-18-04/).) If would probably be better to use something like "nix-shell" for setting up an environment, but that's another set of documentation I'd need to read first.

**Comment by robinp** [comment]
At least for go, it seems to work with Kythe head. Ping if I should have a look at Python.

**Comment by kamahen** [comment]
Has the method of running the frontend server changed? I've attached error output.
[frontend-crash.txt](https://github.com/TreeTide/underhood/files/4087615/frontend-crash.txt)

I also got this after doing `bazel clean --expunge`.

**Comment by robinp** [comment]
@kamahen odd. On my side:

```
~/dev/underhood (develop) $ git status
On branch develop
Your branch is up to date with 'origin/develop'.
```

```
 ~/dev/underhood (develop) $ nix-shell --run 'bazel clean --expunge'
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
ron@rigo ~/dev/underhood (develop) $ nix-shell --run 'bazel run -c opt //treetide/underhood/frontend_server'
Starting local Bazel server and connecting to it...
INFO: Analyzed target //treetide/underhood/frontend_server:frontend_server (34 packages loaded, 2148 targets configured).
INFO: Found 1 target...
Target //treetide/underhood/frontend_server:frontend_server up-to-date:
  bazel-bin/treetide/underhood/frontend_server/frontend_server
INFO: Elapsed time: 33.431s, Critical Path: 23.22s
INFO: 66 processes: 66 processwrapper-sandbox.
INFO: Build completed successfully, 287 total actions
INFO: Build completed successfully, 287 total actions
Up&running!
```

Now, it is possible that I messed up some nix input hash pinning - could check that, but please confirm first you are at commit `ddc292b937661d96e5ee5e6d6d370db6a71fa0b1`. Thanks!

**Comment by kamahen** [comment]
```
$ git pull
Already up to date.
$ git branch
* develop
$ git log -n 2
commit ddc292b937661d96e5ee5e6d6d370db6a71fa0b1 (HEAD -> develop, origin/develop, origin/HEAD)
Merge: e535dc4 a34c264
Author: Robin Palotai <palotai.robin@gmail.com>
Date:   Sun Jan 12 01:19:20 2020 +0100

    Merge pull request #19 from TreeTide/robinp-ui
    
    UI consistency, callsite listing, splitpanes.

commit a34c264400ca39cbda5758488b6ff3b912d331e3 (origin/robinp-ui)
Author: Robin Palotai <palotai.robin@gmail.com>
Date:   Sun Jan 12 01:11:11 2020 +0100

    Splitpanes instead of fixed division of panels.
```
I tried doing `git clean -dxf` in addition to `nix shell --run 'bazel clean--expunge' ... I noticed the following:
```
make[1]: Leaving directory '/home/peter/.cache/bazel/_bazel_peter/c95ab79b7a165f983587a43d5b1ae493/external/rules_haskell_ghc_linux_amd64'
ERROR: /home/peter/src/underhood/treetide/thirdparty/haskell/BUILD:86:1: in haskell_toolchain_library rule //treetide/thirdparty/haskell:network-uri: 
Traceback (most recent call last):
	File "/home/peter/src/underhood/treetide/thirdparty/haskell/BUILD", line 86
		haskell_toolchain_library(name = 'network-uri')
	File "/home/peter/.cache/bazel/_bazel_peter/c95ab79b7a165f983587a43d5b1ae493/external/rules_haskell/haskell/private/haskell_impl.bzl", line 656, in haskell_toolchain_library_impl
		fail(<1 more arguments>)

network-uri is not a toolchain library.
Check that it ships with your version of GHC.
```
and when I re-ran:
```
ERROR: /home/peter/src/underhood/treetide/thirdparty/haskell/BUILD:78:1: in haskell_toolchain_library rule //treetide/thirdparty/haskell:http-types: 
Traceback (most recent call last):
	File "/home/peter/src/underhood/treetide/thirdparty/haskell/BUILD", line 78
		haskell_toolchain_library(name = 'http-types')
	File "/home/peter/.cache/bazel/_bazel_peter/c95ab79b7a165f983587a43d5b1ae493/external/rules_haskell/haskell/private/haskell_impl.bzl", line 656, in haskell_toolchain_library_impl
		fail(<1 more arguments>)

http-types is not a toolchain library.
Check that it ships with your version of GHC.
The following toolchain libraries are available:
...
```

**Comment by robinp** [comment]
Thanks! I pushed a missing `.bazelrc`, please check.

**Comment by kamahen** [comment]
That push seems to fix frontend_server

With `nix-shell --run 'npm run-script start:dev', I got this (and [2020-01-21T00_43_48_424Z-debug.log](https://github.com/TreeTide/underhood/files/4088697/2020-01-21T00_43_48_424Z-debug.log)):
```
> underhood-ui@1.0.0 start:dev /home/peter/src/underhood/treetide/underhood/ui
> webpack-dev-server --mode 'development' --hot

sh: webpack-dev-server: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! underhood-ui@1.0.0 start:dev: `webpack-dev-server --mode 'development' --hot`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the underhood-ui@1.0.0 start:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/peter/.npm/_logs/2020-01-21T00_43_48_424Z-debug.log
```

**Comment by robinp** [comment]
Please exec `nix-shell --run 'npm ci'` the first time, so it downloads half of the internet into `node_modules`.

(Note: there's a way to make node deps be managed by nix as well to make the full build hermetic, but I didn't get to add it to this repo yet).

**Comment by kamahen** [comment]
```
[nix-shell:~/src/underhood]$ npm --version
3.5.2

[nix-shell:~/src/underhood]$ npm ci

Usage: npm <command>

where <command> is one of:
    access, add-user, adduser, apihelp, author, bin, bugs, c,
    cache, completion, config, ddp, dedupe, deprecate, dist-tag,
    dist-tags, docs, edit, explore, faq, find, find-dupes, get,
    help, help-search, home, i, info, init, install,
    install-test, issues, it, la, link, list, ll, ln, login,
    logout, ls, outdated, owner, pack, ping, prefix, prune,
    publish, r, rb, rebuild, remove, repo, restart, rm, root,
    run-script, s, se, search, set, show, shrinkwrap, star,
    stars, start, stop, t, tag, team, test, tst, un, uninstall,
    unlink, unpublish, unstar, up, update, upgrade, v, verison,
    version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm faq          commonly asked questions
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    /home/peter/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@3.5.2 /usr/share/npm
```

**Comment by kamahen** [comment]
I'm going to try deleting everything, cloning the repo and rerunning all the commands.
I'll report back when that's done.

**Comment by kamahen** [comment]
I deleted underhood and pulled it again from the repo.
I deleted all the bazel cache.
```
~/src$ git clone https://github.com/TreeTide/underhood.git
Cloning into 'underhood'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 301 (delta 0), reused 2 (delta 0), pack-reused 293
Receiving objects: 100% (301/301), 246.61 KiB | 1022.00 KiB/s, done.
Resolving deltas: 100% (156/156), done.
~/src$ cd underhood/
~/src/underhood$ nix-shell

[nix-shell:~/src/underhood]$ bazel build -c opt //treetide/...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Analyzed 74 targets (36 packages loaded, 2196 targets configured).
INFO: Found 74 targets...
INFO: Elapsed time: 101.021s, Critical Path: 33.00s
INFO: 73 processes: 73 linux-sandbox.
INFO: Build completed successfully, 305 total actions
```
```
$ cd ../underhood && \
nix-shell --run 'bazel run -c opt //treetide/underhood/frontend_server'
INFO: Analyzed target //treetide/underhood/frontend_server:frontend_server (1 packages loaded, 2 targets configured).
INFO: Found 1 target...
Target //treetide/underhood/frontend_server:frontend_server up-to-date:
  bazel-bin/treetide/underhood/frontend_server/frontend_server
INFO: Elapsed time: 0.748s, Critical Path: 0.22s
INFO: 19 processes: 19 linux-sandbox.
INFO: Build completed successfully, 24 total actions
INFO: Running command line: bazel-bin/treetide/underhood/frontend_server/frontenINFO: Build completed successfully, 24 total actions
Up&running!
```
But ...
```
cd ../underhood/treetide/underhood/ui && \
nix-shell --run 'npm run-script start:dev'

> underhood-ui@1.0.0 start:dev /home/peter/src/underhood/treetide/underhood/ui
> webpack-dev-server --mode 'development' --hot

sh: webpack-dev-server: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! underhood-ui@1.0.0 start:dev: `webpack-dev-server --mode 'development' --hot`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the underhood-ui@1.0.0 start:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/peter/.npm/_logs/2020-01-21T01_21_42_266Z-debug.log
Makefile:728: recipe for target 'run-underhood-ui' failed
make: *** [run-underhood-ui] Error 1

~/src/pykythe$ cd ../underhood/
~/src/underhood$ nix-shell

[nix-shell:~/src/underhood]$ npm ci

Usage: npm <command>

where <command> is one of:
    access, add-user, adduser, apihelp, author, bin, bugs, c,
    cache, completion, config, ddp, dedupe, deprecate, dist-tag,
    dist-tags, docs, edit, explore, faq, find, find-dupes, get,
    help, help-search, home, i, info, init, install,
    install-test, issues, it, la, link, list, ll, ln, login,
    logout, ls, outdated, owner, pack, ping, prefix, prune,
    publish, r, rb, rebuild, remove, repo, restart, rm, root,
    run-script, s, se, search, set, show, shrinkwrap, star,
    stars, start, stop, t, tag, team, test, tst, un, uninstall,
    unlink, unpublish, unstar, up, update, upgrade, v, verison,
    version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm faq          commonly asked questions
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    /home/peter/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@3.5.2 /usr/share/npm
```

**Comment by kamahen** [comment]
This fixed things ... the bottom panel now shows. Thanks!
```
nix-shell
cd treetide/underhood/ui/
npm i  # not ci
```

**Comment by robinp** [comment]
Sorry Peter, forgot to say that for the UI (and npm commands) you should
change dir to treetide/underhood/ui, and execute the nix-shell there.

It will set up the right dependencies, including npm with ci command.

**Comment by kamahen** [comment]
npm 3.5.2 doesn't seem to have a `ci` command, only an `i` command, which is what I used.
And, as far as I can tell, the npm that's used by nix-shell is 3.5.2.
(And, yes, it needs to be done in treetid/underhood/ui)

**Comment by robinp** [comment]
Odd.

```
ron@rigo ~/dev/underhood/treetide/underhood/ui (develop) $ nix-shell

[nix-shell:~/dev/underhood/treetide/underhood/ui]$ which npm
/nix/store/8iapi0p7bc8j28ili40mhdgbgk0ivxiz-nodejs-10.18.0/bin/npm

[nix-shell:~/dev/underhood/treetide/underhood/ui]$ npm --version
6.13.4

[nix-shell:~/dev/underhood/treetide/underhood/ui]$ npm help

Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    clean-install, clean-install-test, completion, config,
    create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
    edit, explore, fund, get, help, help-search, hook, i, init,
    install, install-ci-test, install-test, it, link, list, ln,
    login, logout, ls, org, outdated, owner, pack, ping, prefix,
    profile, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview

Specify configs in the ini-formatted file:
    /home/ron/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@6.13.4 /nix/store/8iapi0p7bc8j28ili40mhdgbgk0ivxiz-nodejs-10.18.0/lib/node_modules/npm
```

**Comment by kamahen** [comment]
Perhaps your nix-shell doesn't install npm, so I'm seeing the default Ubuntu npm, which is rather old. I could add another PPA to get a newer version of npm, but that leaves open the question as to why your nix environment doesn't see a newer version.

**Comment by robinp** [comment]
`nodejs` is specified as a dependency in `shell.nix` in `..../ui`, so `nix-shell` should pick that up. The version is pinned exactly.

```
ron@rigo ~/dev/underhood/treetide/underhood/ui (develop) $ which npm
/usr/bin/npm

ron@rigo ~/dev/underhood/treetide/underhood/ui (develop) $ nix-shell --run 'npm --version'
6.13.4

ron@rigo ~/dev/underhood/treetide/underhood/ui (develop) $ nix-shell --run 'which npm'
/nix/store/8iapi0p7bc8j28ili40mhdgbgk0ivxiz-nodejs-10.18.0/bin/npm

ron@rigo ~/dev/underhood/treetide/underhood/ui (develop) $ nix --version
nix (Nix) 2.2.2
```
What is your nix version? Maybe it doesn't use `shell.nix` in `--run` mode? Just a random idea, short of other sensible.

**Comment by kamahen** [comment]
How strange ... it's now working. Perhaps the last `npm i` fixed things? (but that's hard to believe)

Anyway, I suppose we can close this issue.

**Comment by robinp** [comment]
Thanks, closing - just a remark. `install` (`i`) might have updated the `package[-lock].json` files with newer versions of the deps. `ci` is supposed to not do that, just fetch the given locked versions.

*Edit*: Thanks for being tenacious in tracking down this thread!
